version: "3.7"

services:
  tasker:
    container_name: tasker
    build: ./
    env_file:
      - ./.env
    ports:
      - 8080:8080
    command: make start
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
